### PR TITLE
fix instruct, but sparse reg breaks

### PR DESCRIPTION
**Pull request by GiggleLiu**
This fixes the ambiguity error in https://github.com/QuantumBFS/Yao.jl/issues/268

@Roger-luo The sparse register tests break now, do you know how to fix it?

### CODE REVIEW

**Comment by Roger-luo** [comment]
I think I need to fix CI first.

**Comment by Roger-luo** [comment]
OK I don't know when did this happen, but it seems even on master we are having some ambiguity issue.

**Comment by Roger-luo** [comment]
@GiggleLiu can you merge master branch so this PR triggers CI?

**Comment by GiggleLiu** [comment]
@Roger-luo Now the CI runs, but there is an error. Do you know why it errors?

**Comment by Roger-luo** [comment]
should be fixed now

**Pull request closed without merging**
