### PR TITLE
fix partial_tr

### PR DESCRIPTION
**Pull request by Roger-luo**
`partial_tr` cannot be use normalize in symbolic mode.

### CODE REVIEW

**Comment by Roger-luo** [comment]
It's quite simple. I need it for my assignment, I'll merge this first let's see if there are other thing doesn't work later.

**Comment by GiggleLiu** [comment]
build failed

**Comment by Roger-luo** [comment]
SWAP gets segment fault, doesn't seem related to this PR. @GiggleLiu

**Comment by Roger-luo** [comment]
can you tag a new version after you merge this PR? thx @GiggleLiu I've bump the version number to `v0.2.1`

**Comment by Roger-luo** [comment]
test passed I'll merge this first.

**Pull request merged**
